= Python
Vladimir Fejsov <fejsov87@gmail.com>
:icons: font
:email: fejsov87@gmail.com
:linkattrs:
:toc:

.The Zen of Python
[quote, Tim Peters]
____
[%hardbreaks]
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
____

== Introduction

=== What Is Python?
Python is an open source softwer, created by Dutch programmer Guido van Rossum. Its dynamic nature and concise code structure make it easy to learn and use.

=== What Python Can Do?
With Python programming language it is posible to accomplish wide variety of tasks. Some of domains where python can be used are:

* System Programming
* Internet Programming
* Numeric and Scientific Programming
* Game Programming
* Image Processing
* Data Processing

=== What Are Advantages Compared To Other Programming Languages?
Major benefits of using Python are:

* Code readability
* Developing speed
* Program portability
* Wide range of prebuilt and third-party libraries

=== What Are Downsides?
Only significant disadventage of Python compared to fully compiled languages like C or C++ is its execution speed for some tasks. However, many tasks that require execution speed are run at C speed, because they are handled by compiled C code inside the Python interpreter. For other tasks that haven't appropriate C compiled code inside interpreter, it is posible to use compiled extensions written in some other language by linking them into the Python program. A best example for this solution is the NumPy librarie, used for numeric programming tasks.

=== Versions
There are two families of the Python versions used today, Python 2 and Python 3. Each of these version has subversions. Python 2.7 is the last release of the 2.x series. In November 2014, it was announced that Python 2.7 would be supported until 2020, but users were encouraged to move to Python 3 as soon as possible. Because of that, this book will use Python 3.7, last stable release of the 3.X series in time when this book is written.

=== Features
Pyton is interpretative, dynamic, object oriented scripting langauge. Let's look closely to each of these features.

==== Interpretative Language
Python package, as currently implemented, contains a program known as interpreter. An interpreter is a program that executes other programs, running through program code and executing it line-by-line. As it analyses every line, an interpreter is slower than running compiled code but it can take less time to interpret program code than to compile and then run it — this is very useful when prototyping and testing code. Interpreters are written for multiple platforms, this means code written once can be run immediately on different systems without having to recompile for each.

==== Dynamic Language
==== Object Oriented Language
In Python, everything (integers, strings, list, dictionaries, functions, modules ...) is an object, and all objects are `first class` objects. The best description of this was given by the creator himself:

[quote, Guido van Rossum]
____
One of my goals for Python was to make it so that all objects were "first class." By this, I meant that I wanted all 	objects that could be named in the language (e.g., integers, strings, functions, classes, modules, methods, etc.) to 	have equal status. That is, they can be assigned to variables, placed in lists, stored in dictionaries, passed as 		arguments, and so forth.
____

Every object in Python has its id, type and content:

id::
	A unique identifier of an object, represent as integer returned by built-in function id(object_reference_name). Object id can not be changed.

type::
	A type of the given object, returned by built-in function type(object_reference_name). It gives some usefull information about objects of that type (How much memory needs to be allocated to store object, which attributes and methods they have, etc). Object type can not be changed.

content::
	Content of some objects can be changed without changing its id or type (modify in place), for others it's not allowed.

==== Scripting Language

=== How Python Runs Program?
If you wish to execute Python code, you must run that code throught Python interpreter. Roughly, there are two steps that Python interpreter do in the proccess of executing Python script.

First step is to compile program source code into format called _byte code_. Byte code is lower-level, platform-independent representation of original sorce code. In this step, every statement in source code is translated into group of byte code instructions. This kind of code is faster than program source code.

Once compiled, source code can be saved into file, and can be used next time skipping compilation step. This provide startup speed optimization. For Python 3.2 and later, this byte code is stored in subdirectory named \\__pycache__ alongside source code file. Naming convention for files inside \\__pycache__ directory is that file name identifies Python version used for compiling, ending with __.pyc__ extension (e.g., spam.cpython-36.pyc). This applies only to files that have been imported, not for top-level scripts or code typed at the interactive prompt.

Next time, when program is executed, Python interpreter will search \\__pycache__ directory for file with appropriate name (name that matches script name and version of Python interpreter that runs program). If such file exists, and if it is up-to-date, Python will load that file and skip compilation step. Otherwise, if compiled version of source code not exists or if source code is modified in the meantime, compiling step is performed.

TODO: image primer pycache

Second step is to execute instructions from byte code, one by one. This task is handled by Python Virtual Machine (PVM). PVM is code loop that iterates through byte code and in each iteration pulls out and processes one instruction at a time.

TODO: image full proccess

=== A Programmer Perspective

