= Python
Vladimir Fejsov <fejsov87@gmail.com>
:icons: font
:email: fejsov87@gmail.com
:linkattrs:
:toc:

.The Zen of Python
[quote, Tim Peters]
____
[%hardbreaks]
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
____

== Introduction

=== What Is Python?
Python is an open source softwer, created by Dutch programmer Guido van Rossum. Its dynamic nature and concise code structure make it easy to learn and use.

=== What Python Can Do?
With Python programming language it is posible to accomplish wide variety of tasks. Some of domains where python can be used are:

* System Programming
* Internet Programming
* Numeric and Scientific Programming
* Game Programming
* Image Processing
* Data Processing

=== What are advantages compared to other programming languages?
Major benefits of using Python are:

* Code readability
* Developing speed
* Program portability
* Wide range of prebuilt and third-party libraries

=== What Are Downsides?
Only significant disadventage of Python compared to fully compiled languages like C or C++ is its execution speed for some tasks. However, many tasks that require execution speed are run at C speed, because they are handled by compiled C code inside the Python interpreter. For other tasks that haven't appropriate C compiled code inside interpreter, it is posible to use compiled extensions written in some other language by linking them into the Python program. A best example for this solution is the NumPy librarie, used for numeric programming tasks.
