= Python
Vladimir Fejsov <fejsov87@gmail.com>
:icons: font
:email: fejsov87@gmail.com
:linkattrs:
:toc:

.The Zen of Python
[quote, Tim Peters]
____
[%hardbreaks]
Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
____

== Introduction

=== What Is Python?
Python is an open source softwer, created by Dutch programmer Guido van Rossum. Its dynamic nature and concise code structure make it easy to learn and use.

=== What Python Can Do?
With Python programming language it is posible to accomplish wide variety of tasks. Some of domains where python can be used are:

* System Programming
* Internet Programming
* Numeric and Scientific Programming
* Game Programming
* Image Processing
* Data Processing

=== What Are Advantages Compared To Other Programming Languages?
Major benefits of using Python are:

* Code readability
* Developing speed
* Program portability
* Wide range of prebuilt and third-party libraries

=== What Are Downsides?
Only significant disadventage of Python compared to fully compiled languages like C or C++ is its execution speed for some tasks. However, many tasks that require execution speed are run at C speed, because they are handled by compiled C code inside the Python interpreter. For other tasks that haven't appropriate C compiled code inside interpreter, it is posible to use compiled extensions written in some other language by linking them into the Python program. A best example for this solution is the NumPy librarie, used for numeric programming tasks.

=== Versions
There are two families of the Python versions used today, Python 2 and Python 3. Each of these version has subversions. Python 2.7 is the last release of the 2.x series. In November 2014, it was announced that Python 2.7 would be supported until 2020, but users were encouraged to move to Python 3 as soon as possible. Because of that, this book will use Python 3.7, last stable release of the 3.X series in time when this book is written.

=== Features
Pyton is interpretative, dynamic, object oriented scripting langauge. Let's look closely to each of these features.

==== Interpretative Language
Python package, as currently implemented, contains a program known as interpreter. An interpreter is a program that executes other programs, running through program code and executing it line-by-line. As it analyses every line, an interpreter is slower than running compiled code but it can take less time to interpret program code than to compile and then run it — this is very useful when prototyping and testing code. Interpreters are written for multiple platforms, this means code written once can be run immediately on different systems without having to recompile for each.

==== Dynamic Language
==== Object Oriented Language
In Python, everything (integers, strings, list, dictionaries, functions, modules ...) is an object, and all objects are `first class` objects. The best description of this was given by the creator himself:

[quote, Guido van Rossum]
____
One of my goals for Python was to make it so that all objects were "first class." By this, I meant that I wanted all 	objects that could be named in the language (e.g., integers, strings, functions, classes, modules, methods, etc.) to 	have equal status. That is, they can be assigned to variables, placed in lists, stored in dictionaries, passed as 		arguments, and so forth.
____

Every object in Python has its id, type and content:

id::
	A unique identifier of an object, represent as integer returned by built-in function id(object_reference_name). Object id can not be changed.

type::
	A type of the given object, returned by built-in function type(object_reference_name). It gives some usefull information about objects of that type (How much memory needs to be allocated to store object, which attributes and methods they have, etc). Object type can not be changed.

content::
	Content of some objects can be changed without changing its id or type (modify in place), for others it's not allowed.

==== Scripting Language


